name: 'Get AVD Info'
description: 'Get the AVD info based on its API level.'
inputs:
  api-level:
    required: true
    description: The API level used in workflow
outputs:
  arch:
    value: ${{ steps.get-avd-arch.outputs.arch }}
    description: The architecture used

runs:
  using: "composite"
  steps:
    - id: get-avd-arch
      run: echo "arch=$(if [ ${{ inputs.api-level }} -ge 30 ]; then echo x86_64; else echo x86; fi)" >> $GITHUB_OUTPUT
      shell: bash
